### ISSUE TITLE
pos_report_session_summary Error when printing the session summary.

### ISSUE THREAD

**Issue by anmarmo1** [OCA/pos#1092]
## Module
[pos_report_session_summary](https://github.com/OCA/pos/tree/15.0/pos_report_session_summary)

## Describe the bug
When printing the session summary for both an open and closed session, it produces a format error.

**Affected versions**:
15.0
## To Reproduce

1.Go to session
2. Click on print session summary
3. After clicking, this error occurs

Traceback (most recent call last):
  File "/opt/odoo/addons/web/controllers/main.py", line 2000, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/opt/odoo/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1929, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/addons/account/models/ir_actions_report.py", line 55, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "/opt/odoo/odoo/addons/base/models/ir_actions_report.py", line 902, in _render_qweb_pdf
    html = self_sudo.with_context(context)._render_qweb_html(res_ids, data=data)[0]
  File "/opt/odoo/odoo/addons/base/models/ir_actions_report.py", line 946, in _render_qweb_html
    return self._render_template(self.report_name, data), 'html'
  File "/opt/odoo/odoo/addons/base/models/ir_actions_report.py", line 681, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 1992, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/opt/odoo/addons/web_editor/models/ir_ui_view.py", line 29, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo/addons/base/models/ir_ui_view.py", line 2000, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/opt/odoo/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/opt/odoo/odoo/addons/base/models/ir_qweb.py", line 76, in _render
    result = super()._render(template, values=values, **compile_options)
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 134, in _render
    result = ''.join(rendering)
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 223, in render_template
    raise QWebException("Error when render the template", self, options,
odoo.addons.base.models.qweb.QWebException: 'str' object has no attribute 'decimal_places'
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/qweb.py", line 219, in render_template
    yield from compiled_fn(self, values, log)
  File "<template_1233>", line 631, in template_1233
  File "<template_1233>", line 619, in t_call_content
  File "<template_1233>", line 243, in t_call_content
  File "/opt/odoo/odoo/addons/base/models/ir_qweb.py", line 336, in _get_field
    content = converter.record_to_html(record, field_name, field_options)
  File "/opt/odoo/odoo/addons/base/models/ir_qweb_fields.py", line 481, in record_to_html
    return super(MonetaryConverter, self).record_to_html(record, field_name, options)
  File "/opt/odoo/odoo/addons/base/models/ir_qweb_fields.py", line 120, in record_to_html
    return False if value is False else record.env[self._name].value_to_html(value, options=options)
  File "/opt/odoo/odoo/addons/base/models/ir_qweb_fields.py", line 433, in value_to_html
    fmt = "%.{0}f".format(display_currency.decimal_places)
AttributeError: 'str' object has no attribute 'decimal_places'

Error when render the template
AttributeError: 'str' object has no attribute 'decimal_places'
Template: 1233
Path: /t/t/t/t/div/table/tbody/tr/td[3]/span
Node: <span t-field="statement.balance_start" t-options="{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: &quot;statement.currency_id&quot;}"/>

**Comment by anmarmo1** [comment]
merged the PR that solves this problem
