### ISSUE TITLE
[16.0] build broken by pos_order_to_sale_order_sale_financial_risk

### ISSUE THREAD

**Issue by simahawk** [OCA/pos#1236]
```
024-09-19 06:36:54,694 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Enable chrome headless console log notification 
2024-09-19 06:36:54,694 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Chrome headless enable page notifications 
2024-09-19 06:36:55,129 415 INFO odoo odoo.addons.base.models.res_users: Login successful for db:odoo login:accountman from n/a 
2024-09-19 06:36:55,130 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Setting session cookie in browser 
2024-09-19 06:36:55,131 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Open "http://127.0.0.1:8069/pos/ui?config_id=21" in browser 
2024-09-19 06:36:55,131 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Navigating to: "http://127.0.0.1:8069/pos/ui?config_id=21" 
2024-09-19 06:36:55,134 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Navigation result: {'frameId': 'C30EA8C6FE2E80099BEC66269A615DE2', 'loaderId': 'C25ED8CE835B79DB3EE01A3916E2CECC', 'errorText': 'net::ERR_ABORTED'} 
2024-09-19 06:36:55,134 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Evaluate ready code "odoo.__DEBUG__.services['web_tour.tour'].tours['SaleOrderConfirmFinancialRiskPosCompatibility'].ready" 
2024-09-19 06:37:55,139 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Deleting cookies and clearing local storage 
2024-09-19 06:37:55,145 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Navigating to: "about:blank" 
2024-09-19 06:37:55,146 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Navigation result: {'frameId': 'C30EA8C6FE2E80099BEC66269A615DE2', 'loaderId': 'B2CEF74A576425186DD2A831A1BF1871'} 
2024-09-19 06:37:55,146 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: Waiting for frame 'C30EA8C6FE2E80099BEC66269A615DE2' to stop loading 
2024-09-19 06:37:55,150 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui.TestUi: waiting for threads: [] 
2024-09-19 06:37:55,150 415 INFO odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui: ====================================================================== 
2024-09-19 06:37:55,151 415 ERROR odoo odoo.addons.pos_order_to_sale_order_sale_financial_risk.tests.test_pos_ui: ERROR: TestUi.test_pos_order_to_sale_order_financial_risk
Traceback (most recent call last):
  File "/opt/odoo/odoo/tests/common.py", line 1163, in _websocket_request
    return f.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/pos/pos/pos_order_to_sale_order_sale_financial_risk/tests/test_pos_ui.py", line 19, in test_pos_order_to_sale_order_financial_risk
    self.start_tour(
  File "/opt/odoo/odoo/tests/common.py", line 1857, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/opt/odoo/odoo/tests/common.py", line 1825, in browser_js
    self.assertTrue(self.browser._wait_ready(ready), 'The ready "%s" code was always falsy' % ready)
  File "/opt/odoo/odoo/tests/common.py", line 1424, in _wait_ready
    result = self._websocket_request('Runtime.evaluate', params={
  File "/opt/odoo/odoo/tests/common.py", line 1165, in _websocket_request
    raise TimeoutError(f'{method}({params or ""})')
TimeoutError: Runtime.evaluate({'expression': "try { odoo.__DEBUG__.services['web_tour.tour'].tours['SaleOrderConfirmFinancialRiskPosCompatibility'].ready } catch {}", 'awaitPromise': True})
 
```

https://github.com/OCA/pos/actions/runs/10768547830/job/30357586099

**Comment by simahawk** [comment]
@ivs-cetmix @geomer198 could you have a look pls?

**Comment by legalsylvain** [comment]
Thnaks for your investigation.

**Comment by ivs-cetmix** [comment]
Hi @simahawk @legalsylvain , looks weird. Will check asap

**Comment by ivantodorovich** [comment]
It's many modules that are failing 🤔 
Their tours are not even starting

```
2024-09-19 06:27:52,287 415 ERROR odoo odoo.addons.pos_customer_comment.tests.test_module: ERROR: TestUi.test_pos_customer_comment
Traceback (most recent call last):
  File "/opt/odoo/odoo/tests/common.py", line 1163, in _websocket_request
    return f.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/pos/pos/pos_customer_comment/tests/test_module.py", line 17, in test_pos_customer_comment
    self.start_tour(
  File "/opt/odoo/odoo/tests/common.py", line 1857, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/opt/odoo/odoo/tests/common.py", line 1825, in browser_js
    self.assertTrue(self.browser._wait_ready(ready), 'The ready "%s" code was always falsy' % ready)
  File "/opt/odoo/odoo/tests/common.py", line 1424, in _wait_ready
    result = self._websocket_request('Runtime.evaluate', params={
  File "/opt/odoo/odoo/tests/common.py", line 1165, in _websocket_request
    raise TimeoutError(f'{method}({params or ""})')
TimeoutError: Runtime.evaluate({'expression': "try { odoo.__DEBUG__.services['web_tour.tour'].tours['PosCustomerCommentTour'].ready } catch {}", 'awaitPromise': True})
```

```
2024-09-19 06:29:20,558 415 ERROR odoo odoo.addons.pos_discount_all.tests.test_module: FAIL: TestUi.test_pos_discount_all
Traceback (most recent call last):
  File "/__w/pos/pos/pos_discount_all/tests/test_module.py", line 61, in test_pos_discount_all
    self.start_tour(
  File "/opt/odoo/odoo/tests/common.py", line 1857, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/opt/odoo/odoo/tests/common.py", line 1825, in browser_js
    self.assertTrue(self.browser._wait_ready(ready), 'The ready "%s" code was always falsy' % ready)
AssertionError: False is not true : The ready "odoo.__DEBUG__.services['web_tour.tour'].tours['PosDiscountAllTour'].ready" code was always falsy
 ```

```
2024-09-19 06:30:44,332 415 ERROR odoo odoo.addons.pos_order_to_sale_order.tests.test_module: FAIL: TestUi.test_pos_order_to_sale_order
Traceback (most recent call last):
  File "/__w/pos/pos/pos_order_to_sale_order/tests/test_module.py", line 30, in test_pos_order_to_sale_order
    self.start_tour(
  File "/opt/odoo/odoo/tests/common.py", line 1857, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/opt/odoo/odoo/tests/common.py", line 1825, in browser_js
    self.assertTrue(self.browser._wait_ready(ready), 'The ready "%s" code was always falsy' % ready)
AssertionError: False is not true : The ready "odoo.__DEBUG__.services['web_tour.tour'].tours['PosOrderToSaleOrderTour'].ready" code was always falsy
 ```

```
2024-09-19 06:31:53,424 415 ERROR odoo odoo.addons.pos_partner_location_abstract.tests.test_pos_ui: ERROR: TestPosUI.test_pos_partner_lang_lng
Traceback (most recent call last):
  File "/opt/odoo/odoo/tests/common.py", line 1163, in _websocket_request
    return f.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/pos/pos/pos_partner_location_abstract/tests/test_pos_ui.py", line 14, in test_pos_partner_lang_lng
    self.start_tour(
  File "/opt/odoo/odoo/tests/common.py", line 1857, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/opt/odoo/odoo/tests/common.py", line 1825, in browser_js
    self.assertTrue(self.browser._wait_ready(ready), 'The ready "%s" code was always falsy' % ready)
  File "/opt/odoo/odoo/tests/common.py", line 1424, in _wait_ready
    result = self._websocket_request('Runtime.evaluate', params={
  File "/opt/odoo/odoo/tests/common.py", line 1165, in _websocket_request
    raise TimeoutError(f'{method}({params or ""})')
TimeoutError: Runtime.evaluate({'expression': "try { odoo.__DEBUG__.services['web_tour.tour'].tours['PartnerDetailTour'].ready } catch {}", 'awaitPromise': True})
 ```

```
2024-09-19 06:33:00,311 415 ERROR odoo odoo.addons.pos_product_packaging_container_deposit.tests.test_deposit: ERROR: TestUi.test_pos_order_to_sale_order
Traceback (most recent call last):
  File "/opt/odoo/odoo/tests/common.py", line 1163, in _websocket_request
    return f.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 460, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__w/pos/pos/pos_product_packaging_container_deposit/tests/test_deposit.py", line 118, in test_pos_order_to_sale_order
    self.start_tour(
  File "/opt/odoo/odoo/tests/common.py", line 1857, in start_tour
    return self.browser_js(url_path=url_path, code=code, ready=ready, **kwargs)
  File "/opt/odoo/odoo/tests/common.py", line 1825, in browser_js
    self.assertTrue(self.browser._wait_ready(ready), 'The ready "%s" code was always falsy' % ready)
  File "/opt/odoo/odoo/tests/common.py", line 1424, in _wait_ready
    result = self._websocket_request('Runtime.evaluate', params={
  File "/opt/odoo/odoo/tests/common.py", line 1165, in _websocket_request
    raise TimeoutError(f'{method}({params or ""})')
TimeoutError: Runtime.evaluate({'expression': "try { odoo.__DEBUG__.services['web_tour.tour'].tours['TestDepositProduct'].ready } catch {}", 'awaitPromise': True})
 ```

etc... (many others)

**Comment by legalsylvain** [comment]
Hi @ivantodorovich thanks for the investigation. 

It is maybe unrelated to PoS. See https://github.com/OCA/pos/pull/1226#issuecomment-2360980494

**Comment by pedrobaeza** [comment]
Already fixed in https://github.com/OCA/oca-ci/pull/78

**Comment by legalsylvain** [comment]
Thanks !
