### ISSUE TITLE
[10.0]POS_loyalty QWeb2: Template 'LoyaltyButton' not found

### ISSUE THREAD

**Issue by JohndeWaal** [OCA/pos#208]
after moving Odoo to a new server POS starts with a black screen after loading. Chrome browser development tool shos this error in the console:

Uncaught Error: QWeb2: Template 'LoyaltyButton' not found
    at Object.exception (https://myserver/web/content/595-32fb078/web.assets_common.js:2908:7)
    at Engine._render (https://myserver/web/content/595-32fb078/web.assets_common.js:2953:103)
    at Engine.render (https://myserver/web/content/595-32fb078/web.assets_common.js:2949:151)
    at Class.renderElement (https://myserver/web/content/595-32fb078/web.assets_common.js:3113:1073)
    at Class.renderElement (https://myserver/web/content/698-1b4adab/point_of_sale.assets.js:337:168)
    at Class.prototype.(anonymous function) [as renderElement] (https://myserver/web/content/595-32fb078/web.assets_common.js:3010:559)
    at https://myserver/web/content/595-32fb078/web.assets_common.js:3113:917
    at https://myserver/web/content/595-32fb078/web.assets_common.js:547:681
    at fire (https://myserver/web/content/595-32fb078/web.assets_common.js:541:299)
    at Object.add [as done] (https://myserver/web/content/595-32fb078/web.assets_common.js:542:467)

I've tried to uninstall pos_loyalty and installed it again with the latest version, that makes no difference. version number is 10.0.1.0.0

**Comment by JohndeWaal** [comment]
Issue solved after Odoo server restart. I skipped that step after I installed this module...
