### ISSUE TITLE
pos_pricelist - Uncaught TypeError: this.product.get_price is not a function

### ISSUE THREAD

**Issue by crsilveira** [OCA/pos#274]
Odoo 10.0 
 
Uncaught TypeError: this.product.get_price is not a function
http://127.0.0.1:8069/pos_pricelist/static/src/js/models.js:230
Traceback:
TypeError: this.product.get_price is not a function
    at child.models.Orderline.set_quantity (http://127.0.0.1:8069/pos_pricelist/static/src/js/models.js:230:46)
    at child.initialize (http://127.0.0.1:8069/point_of_sale/static/src/js/models.js:1076:14)
    at child.models.Orderline.initialize (http://127.0.0.1:8069/pos_pricelist/static/src/js/models.js:207:31)
    at child.Backbone.Model (http://127.0.0.1:8069/web/static/lib/backbone/backbone.js:256:21)
    at child [as constructor] (http://127.0.0.1:8069/web/static/lib/backbone/backbone.js:1541:41)
    at new child (http://127.0.0.1:8069/web/static/lib/backbone/backbone.js:1541:41)
    at child.add_product (http://127.0.0.1:8069/point_of_sale/static/src/js/models.js:1987:20)
    at Class.click_product (http://127.0.0.1:8069/point_of_sale/static/src/js/screens.js:1236:33)
    at Object.click_product_action (http://127.0.0.1:8069/point_of_sale/static/src/js/screens.js:1207:59)
    at HTMLSpanElement.click_product_handler (http://127.0.0.1:8069/point_of_sale/static/src/js/screens.js:1078:21)

models.js:230 Uncaught TypeError: this.product.get_price is not a function
    at child.models.Orderline.set_quantity (models.js:230)
    at child.initialize (models.js:1076)
    at child.models.Orderline.initialize (models.js:207)
    at child.Backbone.Model (backbone.js:256)
    at child [as constructor] (backbone.js:1541)
    at new child (backbone.js:1541)
    at child.add_product (models.js:1987)
    at Class.click_product (screens.js:1236)
    at Object.click_product_action (screens.js:1207)
    at HTMLSpanElement.click_product_handler (screens.js:1078)

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem in runbot (https://runbot.odoo-community.org/runbot/repo/github-com-oca-pos-184), once the 10.0 build is done

**Comment by rodrig92** [comment]
In my case, this error is because I have installed pos_cache module and it seems that they are incompatible...
I'm trying to fix it but is complicate for me.

**Comment by zeroheure** [comment]
Same here. In Odoo 10.0 `pos_pricelist` and `pos_cache` can't be installed together.

**Comment by zeroheure** [comment]
Same on runbot.

**Comment by Cedric-Pigeon** [comment]
Did anyone clarify this issue? I am facing the same error message

**Comment by rousseldenis** [comment]
@Yajo @pedrobaeza Any news about this ?

**Comment by pedrobaeza** [comment]
Sorry, we have abandon both the use of 10.0 and of that module, so other needs to take care about this.

**Comment by Cedric-Pigeon** [comment]
ok, thanks. @sbejaoui will have a look.

**Comment by zeroheure** [comment]
commit https://github.com/acsone/pos/commit/d6a704f55fff35ac0149e54e72420ff5946794f3 solved this
