### ISSUE TITLE
Odoo 9: pos_pricelist 

### ISSUE THREAD

**Issue by Mitconsulting** [OCA/pos#283]
Hello,
I need help. I'm trying to install the pos_pricelist module on od0o 9 but the installation goes into error. Here is the error:

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\http.py", line 650, in _handle_exception
 File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\http.py", line 687, in dispatch
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\http.py", line 323, in _call_function
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\http.py", line 316, in checked_call
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\http.py", line 966, in __call__
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\http.py", line 516, in response_wrap
  File "C:\Program Files\Odoo 9.0-20171129\server\openerp\addons\web\controllers\main.py", line 899, in call_button
  File "C:\Program Files\Odoo 9.0-20171129\server\openerp\addons\web\controllers\main.py", line 887, in _call_kw
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files\Odoo 9.0-20171129\server\openerp\addons\base\module\module.py", line 459, in button_immediate_install
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files\Odoo 9.0-20171129\server\openerp\addons\base\module\module.py", line 534, in _button_immediate_function
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\modules\registry.py", line 386, in new
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\modules\loading.py", line 340, in load_modules
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\modules\loading.py", line 239, in load_marked_modules
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\modules\loading.py", line 156, in load_module_graph
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\modules\loading.py", line 98, in _load_data
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\tools\convert.py", line 849, in convert_file
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\tools\convert.py", line 932, in convert_xml_import
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\tools\convert.py", line 799, in parse
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\tools\convert.py", line 802, in parse
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\tools\convert.py", line 705, in _tag_record
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files\Odoo 9.0-20171129\server\openerp\addons\base\ir\ir_model.py", line 1162, in _update
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files\Odoo 9.0-20171129\server\openerp\addons\base\ir\ir_ui_view.py", line 366, in create
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\api.py", line 250, in wrapper
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\api.py", line 354, in old_api
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\models.py", line 4174, in create
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\api.py", line 490, in new_api
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\models.py", line 4371, in _create
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\api.py", line 248, in wrapper
  File "C:\Program Files\Odoo 9.0-20171129\server\.\openerp\models.py", line 1281, in _validate_fields
ParseError: "Invalid view definition

Dettagli dell'Errore:
View inheritance may not use attribute 'string' as a selector.

Contesto errore:
Vista `pos.order`
[view_id: 958, xml_id: n/d, model: pos.order, parent_id: 849]
None" while parsing file:///c:/program%20files/odoo%209.0-20171129/server/openerp/addons/pos_pricelist/views/point_of_sale_view.xml:5, near
<record id="view_pos_pos_form" model="ir.ui.view">
            <field name="name">pos.order</field>
            <field name="model">pos.order</field>
            <field name="inherit_id" ref="point_of_sale.view_pos_pos_form"/>
            <field name="arch" type="xml">
               <data><xpath expr="//field[@name='lines']/tree/field[@name='discount']" position="after">
                       <field name="tax_ids" widget="many2many_tags"/>
               </xpath>
                <page string="Payments" position="after">
                    <page string="Taxes">
                        <field name="taxes">
                            <tree editable="bottom" string="Taxes detail">
                                <field name="name"/>
                                <field name="base"/>
                                <field name="amount"/>
                            </tree>
                        </field>
                    </page>
                </page>
                       </data></field>
               </record>

**Comment by legalsylvain** [comment]
Hi. pos_pricelist is not available for the 9.0 serie. ref : https://github.com/OCA/pos/blob/9.0/pos_pricelist/__openerp__.py#L43

You could participate to the test and the review one of the following pending work : 
https://github.com/OCA/pos/pull/186
https://github.com/OCA/pos/pull/267 (better I think)

kind regards.
