### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kelvingarger** [OCA/pos#435]
Hello,

Odoo Point Of Sale on Odoo Server v12 [Windows ]
Have this particular error when selecting a product:
![max stack size error](https://user-images.githubusercontent.com/35907806/71833176-cd82bb00-3082-11ea-888e-49169af33722.JPG)

Details of the error is as follow:

http://localhost:8069/web/content/332-8549c5b/web.assets_common.js:8
Traceback:
RangeError: Maximum call stack size exceeded
    at new _ (http://localhost:8069/web/content/332-8549c5b/web.assets_common.js:8:141)
    at _ (http://localhost:8069/web/content/332-8549c5b/web.assets_common.js:8:209)
    at child.compute_all (http://localhost:8069/web/content/475-736ccb2/point_of_sale.assets.js:141:126)
    at http://localhost:8069/web/content/475-736ccb2/point_of_sale.assets.js:143:44
    at Function._.each._.forEach (http://localhost:8069/web/content/332-8549c5b/web.assets_common.js:12:558)
    at _.<computed> [as each] (http://localhost:8069/web/content/332-8549c5b/web.assets_common.js:69:526)
    at child.compute_all (http://localhost:8069/web/content/475-736ccb2/point_of_sale.assets.js:141:135)
    at http://localhost:8069/web/content/475-736ccb2/point_of_sale.assets.js:143:44
    at Function._.each._.forEach (http://localhost:8069/web/content/332-8549c5b/web.assets_common.js:12:558)
    at _.<computed> [as each] (http://localhost:8069/web/content/332-8549c5b/web.assets_common.js:69:526)

Any idea of what could be causing this?

thanks,

**Comment by chienandalu** [comment]
Looks like an infinite loop somewhere. Anyway, in order to get help here you should:

- Relate to any module in this repo. We don't support Odoo core or any non OCA module.
- Give steps to reproduce the issue in a community pos runbot (https://runbot.odoo-community.org/runbot/repo/https-github-com-oca-pos-184)
- If you can reproduce the error, make sure you've got `?debug=assets`in your url to obtain a detailed stack trace.
