### ISSUE TITLE
pos_remove_pos_category - KeyError: 'module'

### ISSUE THREAD

**Issue by saltonmassally** [OCA/pos#57]
Cannot create model field from the UI as this results in an error in 
pos_remove_pos_category/product.py", line 63, in _auto_end

**Comment by andhit-r** [comment]
I also encountered with this problem

**Comment by osadmn** [comment]
Me too. How can we fix this?

**Comment by legalsylvain** [comment]
Hi Can you detail when the error occure, plz, which version of the module, ...

regards.

**Comment by andhit-r** [comment]
Hi @legalsylvain. Here are the details:
1. I clone OCA/pos repo
2. I registered OCA/pos repo into my addons
3. I edit any models through UI. I add custom field trough UI
4. Exception raised:

Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 205, in write
    return super(ir_model,self).write(cr, user, ids, vals, context)
  File "/opt/odoo/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3788, in write
    self._write(old_vals)
  File "/opt/odoo/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3932, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/opt/odoo/odoo/openerp/osv/fields.py", line 798, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/opt/odoo/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/addons/base/ir/ir_model.py", line 400, in create
    model._auto_end(cr, ctx) # actually create FKs!
  File "/opt/odoo/oca_pos/pos_remove_pos_category/product.py", line 79, in _auto_end
    module = context['module']
KeyError: 'module'

As you can see that product.py from pos_remove_pos_category cause this. I even does not install pos_remove_pos_category

**Comment by carlosrve** [comment]
I just uploaded a pull request to fix this.

**Comment by pedrobaeza** [comment]
Closing as there's a PR.
