### ISSUE TITLE
 RuntimeError("cannot set daemon status of active thread") on /hw_proxy/status

### ISSUE THREAD

**Issue by cscocca** [OCA/pos#609]
Hi, i got this error in hw_telium_payment_terminal Odoo 12 CE when visit `http://odoo:8069/hw_proxy/status` or `http://odoo/hw_proxy/status`

2021-02-26 18:00:35,044 16774 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo/python3.7-venv/lib/python3.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/python3.7-venv/lib/python3.7/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo12/odoo/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo12/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo12/odoo/odoo/http.py", line 1320, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo12/odoo/odoo/http.py", line 1293, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo/python3.7-venv/lib/python3.7/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo12/odoo/odoo/http.py", line 1488, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo12/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/odoo12/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/odoo/addons/http_routing/models/ir_http.py", line 403, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo12/odoo/addons/website/models/ir_http.py", line 195, in _handle_exception
    return super(Http, cls)._handle_exception(exception)
  File "/opt/odoo12/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 776, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/opt/odoo12/odoo/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/hw_proxy/controllers/main.py", line 82, in status_http
    statuses = self.get_status()
  File "/opt/odoo12/odoo/addons/hw_proxy/controllers/main.py", line 43, in get_status
    statuses[driver] = drivers[driver].get_status()
  File "/opt/odoo12/odoo12-custom-addons/hw_telium_payment_terminal/controllers/main.py", line 43, in get_status
    self.push_task('status')
  File "/opt/odoo12/odoo12-custom-addons/hw_telium_payment_terminal/controllers/main.py", line 69, in push_task
    self.lockedstart()
  File "/opt/odoo12/odoo12-custom-addons/hw_telium_payment_terminal/controllers/main.py", line 65, in lockedstart
    self.daemon = True
  File "/usr/lib/python3.7/threading.py", line 1136, in daemon
    raise RuntimeError("cannot set daemon status of active thread")
RuntimeError: cannot set daemon status of active thread - - -

Any suggestion?
Thanks

**Comment by cscocca** [comment]
Seam I solved deactivating workers in /etc/odoo.conf in the HardwareProxy Instance

**Comment by chienandalu** [comment]
Ok, closing then
