### ISSUE TITLE
[12.0] pos_invoicing expects singleton registering payment 

### ISSUE THREAD

**Issue by mof-landoo** [OCA/pos#644]
When pos_invoicing is installed if I try to register payment from Accounting/Customers/Invoices -> select some opened invoices (not from POS)  -> Action/Register Payment I get this error:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/mnt/container/odoo12-pre/odoo/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 57801

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/container/odoo12-pre/odoo/odoo/fields.py", line 1065, in __get__
    value = record.env.cache.get(record, self)
  File "/mnt/container/odoo12-pre/odoo/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('account.invoice(57801,).outstanding_credits_debits_widget', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/container/odoo12-pre/odoo/odoo/models.py", line 4765, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/container/odoo12-pre/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/container/odoo12-pre/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/mnt/container/odoo12-pre/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/mnt/container/odoo12-pre/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/container/odoo12-pre/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/container/odoo12-pre/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/container/odoo12-pre/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/container/odoo12-pre/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/mnt/container/odoo12-pre/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/mnt/container/odoo12-pre/odoo/addons/web/controllers/main.py", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "/mnt/container/odoo12-pre/odoo/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/container/odoo12-pre/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/mnt/container/odoo12-pre/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/container/odoo12-pre/odoo/addons/account/models/account_payment.py", line 427, in create_payments
    payments += Payment.create(payment_vals)
  File "<decorator-gen-245>", line 2, in create
  File "/mnt/container/odoo12-pre/odoo/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/mnt/container/odoo12-pre/odoo/addons/account/models/account_payment.py", line 584, in create
    rslt = super(account_payment, self).create(vals)
  File "<decorator-gen-134>", line 2, in create
  File "/mnt/container/odoo12-pre/odoo/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/mnt/container/odoo12-pre/odoo/addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/mnt/container/odoo12-pre/odoo/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/mnt/container/odoo12-pre/odoo/odoo/models.py", line 3554, in create
    vals = self._add_missing_default_values(vals)
  File "/mnt/container/odoo12-pre/odoo/odoo/models.py", line 1717, in _add_missing_default_values
    defaults = self.default_get(list(missing_defaults))
  File "/mnt/container/odoo12-pre/odoo/addons/account/models/account_payment.py", line 571, in default_get
    invoice_defaults = self.resolve_2many_commands('invoice_ids', rec.get('invoice_ids'))
  File "/mnt/container/odoo12-pre/odoo/odoo/models.py", line 4592, in resolve_2many_commands
    for data in records.read(fields):
  File "/mnt/container/odoo12-pre/odoo/odoo/models.py", line 2835, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/mnt/container/odoo12-pre/odoo/odoo/models.py", line 5167, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/mnt/container/odoo12-pre/odoo/odoo/fields.py", line 1069, in __get__
    self.determine_value(record)
  File "/mnt/container/odoo12-pre/odoo/odoo/fields.py", line 1182, in determine_value
    self.compute_value(recs)
  File "/mnt/container/odoo12-pre/odoo/odoo/fields.py", line 1136, in compute_value
    self._compute_value(records)
  File "/mnt/container/odoo12-pre/odoo/odoo/fields.py", line 1127, in _compute_value
    getattr(records, self.compute)()
  File "/mnt/container/odoo12-pre/OCA/pos/pos_invoicing/models/account_invoice.py", line 28, in _get_outstanding_info_JSON
    self.ensure_one()
  File "/mnt/container/odoo12-pre/odoo/odoo/models.py", line 4768, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.invoice(57801, 57820, 57798, 57822)
```

I tried to check this behaviour in runbot, but it's down.

**Comment by legalsylvain** [comment]
Hi @mof-landoo. 

I guess your problem will be fixed by this PR. could you review it, and approve it, if OK ? 
https://github.com/OCA/pos/pull/551


thanks.

**Comment by mof-landoo** [comment]
Thank you @legalsylvain. I couldn't test it in runbot, but I did the changes in my instance and I confirm that is working.
