### ISSUE TITLE
[14.0] pos_reset_search  odoo client error

### ISSUE THREAD

**Issue by eguane** [OCA/pos#705]
Tested localy and with last runbot v14.0 with the same issue.
Error when product selected in POS, no error when pos_resest_search removed from odoo.

![odooerror](https://user-images.githubusercontent.com/35990301/132299277-79b8de84-d26d-4769-88a7-2ce33234eb02.png)

"
Traceback:
TypeError: ProductScreenChildren.find is not a function
at Object._clickProduct (http://3501163-14-0-b4c3db.runbot2.odoo-community.org/web/content/478-2e61d9d/point_of_sale.assets.js:1546:376)
at ProductItem.__trigger (http://3501163-14-0-b4c3db.runbot2.odoo-community.org/web/content/473-f61b625/web.assets_common.js:1267:9)
at ProductItem.owl.Component.__trigger (http://3501163-14-0-b4c3db.runbot2.odoo-community.org/web/content/473-f61b625/web.assets_common.js:1419:17)
at ProductItem.trigger (http://3501163-14-0-b4c3db.runbot2.odoo-community.org/web/content/473-f61b625/web.assets_common.js:1256:33)
at Object.p488.on.click (eval at _compile (http://3501163-14-0-b4c3db.runbot2.odoo-community.org/web/content/473-f61b625/web.assets_common.js:969:178), :18:117)
at invokeHandler (http://3501163-14-0-b4c3db.runbot2.odoo-community.org/web/content/473-f61b625/web.assets_common.js:792:144)
at handleEvent (http://3501163-14-0-b4c3db.runbot2.odoo-community.org/web/content/473-f61b625/web.assets_common.js:796:92)
at HTMLElement.handler (http://3501163-14-0-b4c3db.runbot2.odoo-community.org/web/content/473-f61b625/web.assets_common.js:798:58)"

**Comment by chienandalu** [comment]
@dsolanki-initos You made the `pos_reset_search` migration. Could you take a look?

**Comment by iwkse** [comment]
> @dsolanki-initos You made the `pos_reset_search` migration. Could you take a look?
@dsolanki-initos do you have time to look at this bug?
Thanks

**Comment by rousseldenis** [comment]
@dsolanki-initos I confirm the bug here

**Comment by legalsylvain** [comment]
Hi. 
Here is the PR of the migration https://github.com/OCA/pos/pull/651
CC : author & reviewers : @ivantodorovich, @fshah-initos, @dsolanki-initos.

That's quite annoying, because runbot is broken since monthes.
2 options I see : 
- fixing the problem. (I personnaly don't have time to do it).
- disabling the module (``installable = False``) until it is fixed.

Propose to let the current issue opened until end of January. If not fixed, I'll disable the module. Are you ok with that ?

thanks.

Note : @dsolanki-initos : asking for review is one thing, but answering is also great. ;-)
see : 
![image](https://user-images.githubusercontent.com/3407482/149336507-5cb1def0-2a44-4f15-9cbe-07e2f74fee56.png)

**Comment by rousseldenis** [comment]
@legalsylvain I've got the solution

**Comment by rousseldenis** [comment]
https://github.com/OCA/pos/pull/749

**Comment by dsolanki-initos** [comment]
I will check the issue once i get the time for it.

**Comment by legalsylvain** [comment]
Hi. #749 Finally merged.

@dsolanki-initos : It would be great if you had the responsiveness you demand from others. ;-)
7 months without any answer from you regarding a bug you introduced, but you ask for reviews and merge every week...
