### ISSUE TITLE
[14.0] Error when pushing the magnifying glass button

### ISSUE THREAD

**Issue by Mat-moran** [OCA/pos#721]
Hi,

I am having troubles after updating db when I push the magnifying glass button,

the error is the next one 

```
2021-10-24 08:53:20,795 9556 ERROR prod odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/custom/src/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/addons/point_of_sale/models/pos_order.py", line 722, in export_for_ui
    return self.mapped(self._export_for_ui) if self else []
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5247, in mapped
    return self._mapped_func(func)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5203, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5203, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/opt/odoo/custom/src/odoo/addons/pos_hr/models/pos_order.py", line 26, in _export_for_ui
    result = super(PosOrder, self)._export_for_ui(order)
  File "/opt/odoo/custom/src/odoo/addons/point_of_sale/models/pos_order.py", line 696, in _export_for_ui
    'uid': re.search('([0-9]|-){14}', order.pos_reference).group(0),
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by pedrobaeza** [comment]
And how is this related to any of the modules of this repository? Please give the steps to reproduce the problem in the OCA runbot of this repository.

**Comment by Mat-moran** [comment]
The error is pointing to this commit
https://github.com/odoo/odoo/commit/f5b23781cdf8a9e50c9a1fcd38ec704d4a4513fb

Should I move it to the l10n_es_pos @pedrobaeza? seems to be location related, but not with a specific one so...  

or should I remove this commit from my implementation because is a breaking change? 

In my implementation in one ticker for example:
- l10n_es_unique_id: 00013-003-0022
- pos_reference: TPV030118

**Comment by pedrobaeza** [comment]
Continue in OCA/l10n-spain#1908
