### ISSUE TITLE
[14.0] pos_receipt_hide_price and l10n_es_pos modules incompatibility

### ISSUE THREAD

**Issue by Vtejero** [OCA/pos#863]
## Module
pos_receipt_hide_price and l10n_es_pos

## Describe the bug
When both modules are installed, the database is broken.

## To Reproduce
**V14.0**:

1. Create a clean database
2. Install the modules "pos_receipt_hide_price" and "l10n_es_pos".
3. Enjoying a beautiful blank page

**Additional context**
I paste the error that is printed in the log file.
(My server is in Spanish, I hope it doesn't affect)

2022-10-18 17:33:54,274 1465 ERROR Regalo werkzeug: Error on request:
Traceback (most recent call last):
  File "/root/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/root/odoo/odoo/http.py", line 807, in dispatch
    r = self._call_function(**self.params)
  File "/root/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/root/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/root/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/root/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/root/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/root/odoo/addons/web/controllers/main.py", line 1019, in qweb
    content = HomeStaticTemplateHelpers.get_qweb_templates(mods, db, debug=request.session.debug)
  File "/root/odoo/addons/web/controllers/main.py", line 647, in get_qweb_templates
    return cls(addons, db, debug=debug)._get_qweb_templates()[0]
  File "/root/odoo/addons/web/controllers/main.py", line 638, in _get_qweb_templates
    content, checksum = self._concat_xml(files)
  File "/root/odoo/addons/web/controllers/main.py", line 620, in _concat_xml
    xml = self._compute_xml_tree(addon, fname, contents)
  File "/root/odoo/addons/web/controllers/main.py", line 558, in _compute_xml_tree
    inherited_template = apply_inheritance_specs(parent_tree, xpaths)
  File "/root/odoo/odoo/tools/template_inheritance.py", line 233, in apply_inheritance_specs
    raise ValueError(

 Exception

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/root/odoo/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/root/odoo/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/root/odoo/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/root/odoo/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/root/odoo/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/root/odoo/odoo/http.py", line 1478, in dispatch
    result = ir_http._dispatch()
  File "/root/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/root/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/root/odoo/addons/http_routing/models/ir_http.py", line 508, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/root/odoo/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
  File "/root/odoo/addons/http_routing/models/ir_http.py", line 598, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/root/odoo/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
  File "/root/odoo/odoo/http.py", line 745, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/root/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: El elemento '<xpath expr="//t[@t-if='!isTaxIncluded']/div[1]">' no puede ser localizado en la vista padre - - -

Thanks

**Comment by legalsylvain** [comment]
Hi @Vtejero. 
Just installed both module ``l10n_es_pos`` and ``pos_receipt_hide_price`` on a fresh database.
It works OK.
Are you sure it's a fresh database, and that you don't have other module installed? 
regards.

**Comment by Vtejero** [comment]
Hello,
I have tried on another server and it works, sorry for the inconvenience.
Thank you very much.
Greetings.
