### ISSUE TITLE
[14.0] POS_order_return error payment

### ISSUE THREAD

**Issue by JulienMartinez** [OCA/pos#937]
## Module
POS_order_return

## Describe the bug
The problem on the POS_order_return is related to the option on the POS "stock movement in real time"

## To Reproduce
**Affected versions**: 14.0

1.  Go to POS settings
2. Activate sotck movement in real time
3. Make a sale in the POS
4. Use the button Return items 
5. Make the refund
6. And observe the Error Python

**Expected behavior**
Validate the refund and perform the stock movement of the items

**Comment by legalsylvain** [comment]
Hi @JulienMartinez. thanks for reporting. could you copy paste the python error log ? 
thanks !

**Comment by JulienMartinez** [comment]
Hi @legalsylvain here is the python error , 

regards . 

```python
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo_14/server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo_14/server/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo_14/server/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo_14/server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo_14/server/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo_14/server/odoo/http.py", line 908, in __call__
    return self.method(*args, **kw)
  File "/home/odoo_14/server/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo_14/server/addons/web/controllers/main.py", line 1376, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo_14/server/addons/web/controllers/main.py", line 1364, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo_14/server/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo_14/server/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo_14/additionnal_repositories/OCA-pos/pos_customer_required/models/pos_make_payment.py", line 29, in check
    return super(PosMakePayment, self).check()
  File "/home/odoo_14/server/addons/point_of_sale/wizard/pos_payment.py", line 59, in check
    order._create_order_picking()
  File "/home/odoo_14/additionnal_repositories/OCA-pos/pos_order_return/models/pos_order.py", line 141, in _create_order_picking
    res = wizard.create_returns()
  File "/home/odoo_14/server/addons/stock/wizard/stock_picking_return.py", line 175, in create_returns
    new_picking_id, pick_type_id = wizard._create_returns()
  File "/home/odoo_14/server/addons/delivery/models/stock_picking.py", line 312, in _create_returns
    new_picking, pick_type_id = super(StockReturnPicking, self)._create_returns()
  File "/home/odoo_14/server/addons/stock_account/wizard/stock_picking_return.py", line 18, in _create_returns
    new_picking_id, pick_type_id = super(StockReturnPicking, self)._create_returns()
  File "/home/odoo_14/server/addons/stock/wizard/stock_picking_return.py", line 120, in _create_returns
    new_picking = self.picking_id.copy({
  File "/home/odoo_14/server/odoo/models.py", line 4691, in copy
    self.ensure_one()
  File "/home/odoo_14/server/odoo/models.py", line 5028, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo_14/server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo_14/server/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: stock.picking()

**Comment by legalsylvain** [comment]
Hi. Did you tried to cherry picked that V12 patch ? 
https://github.com/OCA/pos/pull/481

if it works, could you make a PR ? 

than,ks !

**Comment by DorianMAG** [comment]
Hi @JulienMartinez , @legalsylvain .

I was able to reproduce the problem on the runboat .

Regards

**Comment by flotho** [comment]
Hi @JulienMartinez @DorianMAG , could you please propose a PR if it's working ?
Regards

**Comment by anmarmo1** [comment]
The error is reproduced in runboat if the "real time" checkbox in the "Inventory management" section is activated, otherwise it works correctly

![image](https://user-images.githubusercontent.com/15904368/232010003-001c6162-7409-4573-9d77-726d84112fb8.png)

**Comment by chienandalu** [comment]
This is addressed here https://github.com/OCA/pos/pull/981

**Comment by zamberjo** [comment]
This issue is resolved, it can be closed.
